post http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBlbHRzaSIsImlkIjoiNWU3OTExMDdhZmI5Yjk3NWEzMWE1MTI1IiwiaWF0IjoxNTg0OTkyNjAxfQ.Oee7mwWMw9rW2bAWJyCJVQ_gbN1BzZnMk2b4rCUPLz4

{
    "title": "peltsin ploki",
    "author": "Peltsi Mäkelä",
    "url": "http"
}