post http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlNjUiLCJpZCI6IjVlYjJhOGNkZWU2Yzg5MmYxMWVhYjVmNiIsImlhdCI6MTU4ODc2Njk2OX0.8sHOO3zUMybesP9bUfv8mhVzPWR6H1NtGeq9nK7gN3U

{
    "title": "keskiviikko-blogi",
    "author": "keke",
    "url": "https://www.netflix.com/browse"
}